from django.contrib.auth.models import User
from django.db import models


class Message(models.Model):
    """
    This class has an insecure design flaw. An AUTO INCREMENT id (which is automatically generated by Django) is used,
    which means that a third party can easily guess the ids of the messages. This could be used to enumerate every message
    in the system, or delete every message in the system if combined with the flaws in the delete function. This can be
    fixed by using a UUID field for the id.
    For example:
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    """
    sent_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sent_messages')
    sent_to = models.ForeignKey(User, on_delete=models.CASCADE, related_name='received_messages')
    text = models.TextField()
